name: Build and Test

on:
  push:
    branches: [ main, tests, develop ]
  pull_request:
    branches: [ main, tests ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore AvaloniaTests/AvaloniaTests.csproj
      
    - name: Build
      run: dotnet build AvaloniaTests/AvaloniaTests.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test AvaloniaTests/AvaloniaTests.csproj --no-build --configuration Release --verbosity normal --filter "TestCategory!=Manual"
      
    - name: Publish (macOS)
      if: matrix.os == 'macos-latest'
      run: dotnet publish AvaloniaTests/AvaloniaTests.csproj -c Release -r osx-arm64 --self-contained true -o ./publish/osx-arm64
      
    - name: Publish (Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet publish AvaloniaTests/AvaloniaTests.csproj -c Release -r win-x64 --self-contained true -o ./publish/win-x64
      
    - name: Publish (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: dotnet publish AvaloniaTests/AvaloniaTests.csproj -c Release -r linux-x64 --self-contained true -o ./publish/linux-x64
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AvaloniaTests-${{ matrix.os }}
        path: ./publish/
